### PR TITLE
aya-ebpf: use correct types for BPF helper return values

### LINKED ISSUE #1414: aya compile errors on 32-bit armv7 machine
on a raspberry pi (32-bit armv7) running raspian trixie, "pip install mitmproxy" produces the following aya compile errors:

        --> /home/pi/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aya-ebpf-0.1.1/src/args.rs:66:16
         |
      66 |     regs: *mut pt_regs,
         |                ^^^^^^^ not found in this scope
         |
      help: consider importing one of these structs
         |
      13 + use crate::bindings::pt_regs;
         |
      13 + use aya_ebpf_bindings::bindings::pt_regs;
         |
     
... snip, many similar errors

     error[E0308]: mismatched types
         --> /home/pi/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aya-ebpf-0.1.1/src/helpers.rs:412:20
          |
      412 |     read_str_bytes(len, dest)
          |     -------------- ^^^ expected `i64`, found `i32`
          |     |
          |     arguments to this function are incorrect
          |
      note: function defined here
         --> /home/pi/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aya-ebpf-0.1.1/src/helpers.rs:415:4
          |
      415 | fn read_str_bytes(len: i64, dest: &[u8]) -> Result<&[u8], c_long> {
          |    ^^^^^^^^^^^^^^ --------
      help: you can convert an `i32` to an `i64`
          |
      412 |     read_str_bytes(len.into(), dest)
          |                       +++++++

      error[E0308]: mismatched types
         --> /home/pi/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aya-ebpf-0.1.1/src/helpers.rs:563:20
          |
      563 |     read_str_bytes(len, dest)
          |     -------------- ^^^ expected `i64`, found `i32`
          |     |
          |     arguments to this function are incorrect
          |
note: function defined here
         --> /home/pi/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aya-ebpf-0.1.1/src/helpers.rs:415:4
          |
      415 | fn read_str_bytes(len: i64, dest: &[u8]) -> Result<&[u8], c_long> {
          |    ^^^^^^^^^^^^^^ --------
      help: you can convert an `i32` to an `i64`
          |
      563 |     read_str_bytes(len.into(), dest)
          |                       +++++++
          
      error[E0308]: mismatched types
         --> /home/pi/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aya-ebpf-0.1.1/src/helpers.rs:755:27
          |
      755 |                   PrintkArg((x as $via).to_ne_bytes())
          |                   --------- ^^^^^^^^^^^^^^^^^^^^^^^^^ expected an array with a size of 8, found one with a size of 4   
          |                   |
          |                   arguments to this struct are incorrect
      ... 
      761 | / impl_integer_promotion!(
      762 | |   char:  via usize,
      763 | |   u8:    via usize,
      764 | |   u16:   via usize,
      ...   |
      772 | |   isize: via isize,
      773 | | );
          | |_- in this macro invocation
          |
      note: tuple struct defined here
         --> /home/pi/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aya-ebpf-0.1.1/src/helpers.rs:739:12
          |
      739 | pub struct PrintkArg([u8; 8]);
          |            ^^^^^^^^^
          = note: this error originates in the macro `impl_integer_promotion` (in Nightly builds, run with -Z macro-backtrace for more info)
    error[E0308]: mismatched types
         --> /home/pi/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aya-ebpf-0.1.1/src/helpers.rs:779:19
          |
      779 |         PrintkArg((x as usize).to_ne_bytes())
          |         --------- ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected an array with a size of 8, found one with a size of 4
          |         |
          |         arguments to this struct are incorrect
          |         
      note: tuple struct defined here
         --> /home/pi/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aya-ebpf-0.1.1/src/helpers.rs:739:12
          |
      739 | pub struct PrintkArg([u8; 8]);
          |            ^^^^^^^^^

      error[E0308]: mismatched types
         --> /home/pi/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aya-ebpf-0.1.1/src/helpers.rs:787:19
          |
      787 |         PrintkArg((x as usize).to_ne_bytes())
          |         --------- ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected an array with a size of 8, found one with a size of 4
          |         |
          |         arguments to this struct are incorrect
          |         
      note: tuple struct defined here
         --> /home/pi/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aya-ebpf-0.1.1/src/helpers.rs:739:12
          |
      739 | pub struct PrintkArg([u8; 8]);
          |            ^^^^^^^^^

      error[E0308]: mismatched types
         --> /home/pi/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aya-ebpf-0.1.1/src/helpers.rs:834:14
          |
      822 | ) -> i64 {
          |      --- expected `i64` because of return type
      ...
      834 |         0 => printk(fmt_ptr, fmt_size),
          |              ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i64`, found `i32`
          |
      help: you can convert an `i32` to an `i64`
          |
      834 |         0 => printk(fmt_ptr, fmt_size).into(),
          |                                       +++++++
error[E0308]: mismatched types
        --> /home/pi/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aya-ebpf-0.1.1/src/maps/bloom_filter.rs:50:40
         |
      50 |         (ret == 0).then_some(()).ok_or(ret)
         |                                  ----- ^^^ expected `i64`, found `i32`
         |                                  |
         |                                  arguments to this method are incorrect
         |                                  
      help: the return type of this call is `i32` due to the type of the argument passed
        --> /home/pi/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aya-ebpf-0.1.1/src/maps/bloom_filter.rs:50:9
         |
      50 |         (ret == 0).then_some(()).ok_or(ret)
         |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^---^
         |                                        |
         |                                        this argument influences the return type of `ok_or`
      note: method defined here                   
        --> /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/option.rs:1252:12
      help: you can convert an `i32` to an `i64`
         |
      50 |         (ret == 0).then_some(()).ok_or(ret.into())
         |                                           +++++++
      
      error[E0308]: mismatched types                 
        --> /home/pi/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aya-ebpf-0.1.1/src/maps/bloom_filter.rs:62:40
         |
      62 |         (ret == 0).then_some(()).ok_or(ret)
         |                                  ----- ^^^ expected `i64`, found `i32`
         |                                  |
         |                                  arguments to this method are incorrect
         |                                  
      help: the return type of this call is `i32` due to the type of the argument passed
        --> /home/pi/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aya-ebpf-0.1.1/src/maps/bloom_filter.rs:62:9
         |
      62 |         (ret == 0).then_some(()).ok_or(ret)
         |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^---^
         |                                        |
         |                                        this argument influences the return type of `ok_or`

etc  etc.

also confirmed by cloning aya git repo and trying to build.

### PR DESCRIPTION
**Pull request by Brskt**
Complete the `i32` errno migration started in 8962fc79. Errno-only
helpers now return `Result<T, i32>`, non-errno helpers (verdicts, byte
counts) return `c_long`, and internal functions receiving raw helper
returns use `c_long`. `check_bounds_signed` now takes `T: Into<i64>`
to accept all signed/unsigned integer types without manual casts.

This fixes compilation on 32-bit armv7 where `c_long` is `i32`, causing
type mismatches with the previously hardcoded `i64` return types.

The split policy follows the rationale from 8962fc79: the aarch64 JIT
doesn't sign-extend helper return values into the upper 32 bits, so
errno codes must be narrowed to `i32` (`MAX_ERRNO = 4095`). Non-errno
returns (verdicts like `SK_PASS`/`SK_DROP`, byte counts, stack IDs)
keep `c_long` to match the BPF helper ABI.

Fixes: #1414

### Added/updated tests?

- [x] No, and this is why: type-only changes with no behavioral difference
      at runtime. Existing integration tests (bloom_filter, ring_buf,
      stack_trace, sock_ops, etc.) already cover all modified code paths
      and pass on both x86_64 and armv7.

### Checklist

- [x] Rust code has been formatted with `cargo +nightly fmt`.
- [x] All clippy lints have been fixed.
- [x] Unit tests are passing locally with `cargo test`.
- [x] The Integration tests are passing locally.
- [x] I have blessed any API changes with `cargo xtask public-api --bless`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/aya-rs/aya/1525)

### CODE REVIEW

File: ebpf/aya-ebpf/src/lib.rs [hunk 1]
```diff
@@ -144,7 +144,7 @@ pub const fn bpf_f_adj_room_encap_l2(len: u64) -> u64 {
 /// Check if a value is within a range, using conditional forms compatible with
 /// the verifier.
 #[inline(always)]
-pub fn check_bounds_signed(value: i64, lower: i64, upper: i64) -> bool {
+pub fn check_bounds_signed(value: c_long, lower: c_long, upper: c_long) -> bool {
```
Comment (vadorovsky) [inline ebpf/aya-ebpf/src/lib.rs]: I'm not loving the fact that people have to convert integer types manually before calling this helper.

I'm wondering if we could just take a generic type `T: Into<i64>`, so we would practically accept all the smaller signed integer types.

This seems to work with all the integration tests:

```suggestion
pub fn check_bounds_signed<T: Into<i64>>(value: T, lower: T, upper: T) -> bool {
    let value = value.into();
    let lower = lower.into();
    let upper = upper.into();
```

This way we require explicit conversion only for `u64` (and `usize` on 64-bit platforms), but that makes sense, because it's lossy.

@alessandrod do you see any issues with such approach?

**Comment by vadorovsky** [comment]
@Brskt I tried to re-run the netlify jobs, but it didn't seem to work. I guess a rebase and force push will do it.

File: ebpf/aya-ebpf/src/lib.rs (hunk 1 above)
Comment (alessandrod) [reply ebpf/aya-ebpf/src/lib.rs]: nope this seems good

Comment (Brskt) [reply ebpf/aya-ebpf/src/lib.rs]: Done.

**Review by vadorovsky — APPROVED** [review]
